spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lhl?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: lhl

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hr.sb5mybatis.entity
  global-config:
    db-config:
      id-type: auto

